# Generated by Django 4.2.2 on 2023-07-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='cover',
            field=models.URLField(null=True),
        ),
    ]
